version: 2

sources:
  - name: source_table_name
    database: DBT_TEST
    schema: DEV
    tables:
      - name: raw_customerdata
      
      - name: customers
 
      - name: orders
      